server:
  port: 8760
logging:
  logLevel:
    elfLevel: INFO
  level:
    ROOT: INFO
    com.amex: INFO
configServer:
  serviceConfig:
     ############## CSRT Core Processes: #############
    csrt-query-service:
      discovery-client: true
      version: "LATEST"
      ports:
      - "8761"
    router:
      discovery-client: true
      version: "LATEST"
      ports:
      - "8765"
    csrt-portal-api:
      discovery-client: true
      version: "LATEST"
